# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81fa081eb1a7fa5b35fac29f3ca7118dcfc4cef6b64841ffa0a1dd55d1db1d7eabcdf39e69a2a932dfc685093f0a4fbb20f53ba93b3f42fd2aac997482c029b0

test:
  secret_key_base: 7464e2cf0302439960634c5f4c44e9670e0f6637efd5f5d3c260692cff5781185467eaf16d4187fe559406412ada1466942b38aa97d0d793296d4a019b4be6bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
